
export const CHANGE_ACTIVE_PLAYLIST = 'CHANGE_ACTIVE_PLAYLIST';
export const CHANGE_ACTIVE_SONG_ID = 'CHANGE_ACTIVE_SONG_ID';
export const CHANGE_ACTIVE_USER_ID = 'CHANGE_ACTIVE_USER_ID';
export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';

export const CHANGE_PATH = 'CHANGE_PATH';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const CHANGE_SELECTED_PLAYLISTS = 'CHANGE_SELECTED_PLAYLISTS';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const PLAY_SONG = 'PLAY_SONG';
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';

export const RECEIVE_SONG = 'RECEIVE_SONG';

export const RECEIVE_SONGS = 'RECEIVE_SONGS';

export const REQUEST_SONG = 'REQUEST_SONG';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';
